version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app:dev
    expose:
      - 5000
    ports:
    - 5000:5000
    depends_on:
      - db
#        condition: service_healthy
#    volumes:
#      - app-data:/usr/src/app/static

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "library"
      POSTGRES_PASSWORD: "353535"
      POSTGRES_HOST_AUTH_METHOD: "trust"
#    volumes:
#      - db-data:/var/lib/postgresql/data
    ports:
      - "5405:5432"
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5